### ISSUE TITLE
vs2019编译错误

### ISSUE THREAD

**Issue by Skull-Li** [lzpong/RDCMan#1]
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=配置系统未能初始化
  Source=System.Configuration
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   at System.Diagnostics.TraceSource.Initialize()
   at System.ComponentModel.Composition.Diagnostics.TraceSourceTraceWriter.get_CanWriteInformation()
   at System.ComponentModel.Composition.Diagnostics.CompositionTrace.DefinitionContainsNoExports(Type type)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable()
   at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable(Type type, ICompositionElement origin)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(String contractName)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(ImportDefinition definition)
   at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at RdcMan.Program.Main(String[] args)

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
ConfigurationErrorsException: 无法识别的配置节 rdcman。 (D:\www_c#\RDCMan\bin\Release\net48\RDCMan.exe.Config line 6)

不太懂net，看错误提示貌似无法识别app.config line6开始的节点代码

还有就是，能否Releases 的时候一起发布编译版本？

**Comment by lzpong** [comment]
`app.config` 内容有误, 已修正(主版本上)
Release 发布版本程序文件已添加.
